[package]
name = "ironlobe"
version = "0.1.0"
authors = ["jmcph4 <jmcph4@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.9"
ordered-float = "1.0.2"

