name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --all
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Check for unused dependencies
      run: cargo install cargo-machete && cargo machete
    - name: Check for known vulnerabilities in dependencies
      run: cargo install cargo-audit && cargo audit
